# Generated by Django 5.0.1 on 2024-02-18 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='статус'),
        ),
    ]
