# Generated by Django 5.0.1 on 2024-03-03 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0003_dog_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='цена, руб'),
        ),
    ]
